version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - TP5_network
    volumes:
      - type: bind
        source: ./volumeBenefits.txt
        target: /code/volumeBenefits.txt
  mongodb:
    image: mongo
    networks:
      - TP5_network
    volumes:
      - "dbdata:/data/db"
networks:
  TP5_network:
    driver: bridge
volumes:
  dbdata:
